---
- hosts: localhost
  gather_facts: false
  connection: local
  become: yes
  tasks:
  - name: Build containers and expose services
    shell: |
      cd compose
      docker-compose up -d
   