---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Install prerequisites
    apt:
      name: ['python3-pip', 'python3-setuptools', 'virtualenv']
      update_cache: yes
      state: present

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
      dest: "/usr/local/bin/docker-compose"
      mode: 0755