---
- hosts: all
  tasks:
    - name: Install Python3
      become: yes
      apt: name=python3 update_cache=yes state=latest

    - name: Install Git package
      become: yes
      apt: name=git update_cache=yes state=latest

    
